name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: |
          echo "$PWD/node_modules/tree-sitter-cli/" >> "$GITHUB_PATH"
      - run: |
          echo "$PWD"
          ls -R "$PWD"
          echo "$GITHUB_PATH"
          cat "$GITHUB_PATH"
          which tree-sitter
      - uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
