name: Publish package

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@156ae2e02c46e5d628782c49f4c1cfccecf85c9f
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
